### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by LinXiaoTao** [yuqirong/CardSwipeLayout#1]
效果看起来还不错，不过有一点是:
![image](https://cloud.githubusercontent.com/assets/19836925/23696174/8b1e1df2-041d-11e7-8a77-7f40cba8b490.png)
不要定义这种**常量接口**，可以考虑使用**私有构造方法的`final`类**来存放常量。

**Comment by yuqirong** [comment]
为什么这样说，是性能上有什么差别吗？

**Comment by LinXiaoTao** [comment]
这倒不是性能上的，只是一种规范吧。
参考Effective Java第十九条
**接口只用于定义类型**

**Comment by Puppy-Love** [comment]
以前我也用 final 静态变量，感觉好low  现在一直养接口定义啊  看着挺舒服的啊 别人腾讯写的代码也这么玩，没发现什么问题啊
