### ISSUE TITLE
下拉以及上滑的一个问题

### ISSUE THREAD

**Issue by ShineBright2015** [yuqirong/CardSwipeLayout#2]
发现的一个问题：下拉以及上滑出现图片闪烁，希望可以及时修正

**Comment by yuqirong** [comment]
好的，已经重现该问题了。谢谢反馈

**Comment by yuqirong** [comment]
@ShineBright2015 我修改了 RoundImageView 的代码，现在你下载最新的代码试试还有没有这个问题。

**Comment by yuqirong** [comment]
@ShineBright2015 现在将该 issue 关闭，如果还有问题再 reopen
