### ISSUE TITLE
为何要两次缩放

### ISSUE THREAD

**Issue by mrrobot97** [yuqirong/CardSwipeLayout#3]
LayoutManager里面已经对view进行缩放，CardItemTouchHelperCallback的onChildDraw()里没有必要再次对下面的view进行缩放了。

**Comment by yuqirong** [comment]
CardItemTouchHelperCallback 的 onChildDraw() 里面处理的是当用户滑动卡片时卡片“”迭代”的动画效果

**Comment by mrrobot97** [comment]
了解。
